ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1000
ARG PGID=1000
#
RUN set -xe \
    && addgroup -g ${PGID} -S mpd \
    && adduser -u ${PUID} -G mpd -h /home/mpd -D mpd \
    && addgroup pulse \
    && adduser mpd pulse \
    && apk add -Uu --no-cache --purge \
        alsa-lib \
        alsa-plugins-pulse \
        alsa-utils \
        libmpdclient \
        libpulse \
        mpc \
        mpd \
        mpdscribble \
        ympd \
    # && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main/" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories \
    # && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories \
    && apk add -U --no-cache \
        ncmpcpp \
    && rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
# VOLUME /var/lib/mpd/
#
EXPOSE 6600 8000 64801
#
ENTRYPOINT ["/init"]
