#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }
sleep 2; # for mpd to start

YMPD_ARGS="${YMPD_ARGS:- -h localhost -p 6600 -w 64801}";

vecho "Starting YMPD...";
s6-setuidgid ${S6_USER:-alpine} \
exec \
    ympd \
    ${YMPD_ARGS} \
    ;
