#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }
usercmd () { if [ "X${EUID}" != "X0" ]; then ${1} "${@:2}"; else s6-setuidgid ${PUID:-1000}:${PGID:-1000} ${1} "${@:2}"; fi; }

sleep 2; # for mpd to start

YMPD_ARGS="${YMPD_ARGS:- -h localhost -p ${MPD_PORT:-6600} -w 64801}";

vecho "Starting YMPD...";
usercmd \
exec \
    ympd \
    ${YMPD_ARGS} \
    ;
