#!/usr/bin/with-contenv bash
set -e

usercmd () { if [ "X${EUID}" != "X0" ]; then ${1} "${@:2}"; else s6-setuidgid ${PUID:-1000}:${PGID:-1000} ${1} "${@:2}"; fi; }

MPD_CONF="${MPD_CONF:-/etc/mpd.conf}";
MPD_ARGS="${MPD_ARGS:- --stdout}";

usercmd \
exec \
    mpd \
    --no-daemon \
    ${MPD_ARGS} \
    ${MPD_CONF} \
    ;
