#!/usr/bin/with-contenv bash

mkdir -p /var/lib/mpd/database \
     /var/lib/mpd/music \
    /var/lib/mpd/playlists

touch /var/lib/mpd/state
touch /var/lib/mpd/tag_cache

mkdir -p /var/log/mpd/
touch /var/log/mpd/mpd.log

chown -R mpd /var/lib/mpd \
    /var/log/mpd/
